export enum CoachingNotificationType {
  GOOD_MORNING = 'GOOD_MORNING',
  CLASS_REMINDER = 'CLASS_REMINDER',
  CLASS_STARTED = 'CLASS_STARTED',
  MISSED_CLASS = 'MISSED_CLASS',
  TEST_REMINDER = 'TEST_REMINDER',
  FEE_DUE = 'FEE_DUE',
  RESULT_PUBLISHED = 'RESULT_PUBLISHED',
  GOOD_NIGHT = 'GOOD_NIGHT',
  GOOD_AFTERNOON = 'GOOD_AFTERNOON',
}
