import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Questions attached to an assignment. Each row is a snapshot (copied from the
 * question bank or generated by Eddva AI), so later edits to the source
 * assessment never change a published assignment. topic_name is kept for
 * topic-level analytics.
 */
export class CreateAssignmentQuestions1791000000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS assignment_questions (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        assignment_id UUID NOT NULL,
        position INT NOT NULL,
        marks NUMERIC NOT NULL DEFAULT 1,
        topic_name VARCHAR(200),
        source VARCHAR(16) NOT NULL DEFAULT 'manual',
        source_ref VARCHAR(200),
        data JSONB NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_assignment_question_position UNIQUE (assignment_id, position)
      );
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS assignment_questions`);
  }
}
